name: Update develop after master merge

on:
  push:
    branches:
    - master


jobs:
  develop_update:
    runs-on: ubuntu-latest

    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout develop
      run: |
        git fetch origin master develop
        git checkout develop

    - name: Check if branch locked
      run: |
        test -e .locked || exit 1

    - name: Update develop from master
      run: |
        git merge origin/master
        git push origin develop
